language: ruby
rvm:
- 2.2.2
- jruby
- rbx-2

before_script:

script:

- bin/rails g unsakini:config
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare
- bundle exec rake
