# language: ruby
# rvm:
# - 2.2.2
# - jruby-2.2.2
# - rbx-2.2.2

language: node_js
node_js:
  - 6.9.1

before_install:
  - rvm install 2.2.2

bundler_args: --without production

before_script:

script:
- bundle install
- bundle exec rails db:migrate
- bundle exec rspec
- cd angular
- npm i
- node_modules/.bin/ng test --single-run
