# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a9905d139e22fb52a6d861505ded396df2ea4e5780673a420c125eec3647ca8fac218e917de4c34c32cec10e4ae59a76876694398ef3b7582b8a72def8892ebb

test:
  secret_key_base: 65cf027a728a399176eab9faf8dfe0e7f10df1eab7df58266eb205b41ed8c551e633bbcb5e0482bab297102091535e38a7ef2f167206cf694211f59eac53f280

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
